version: '3'
services:
  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
    working_dir: /web
    volumes:
      - ./web:/web
      - /web/node_modules/
    ports:
      - "127.0.0.1:8080:8080"

  trainer-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/trainer
    ports:
      - "127.0.0.1:3000:$PORT"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: http
    depends_on:
      - firebase

  trainer-grpc:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/trainer
    ports:
      - "127.0.0.1:3010:$PORT"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: grpc
    depends_on:
      - firebase

  trainings-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/trainings
    ports:
      - "127.0.0.1:3001:$PORT"
    env_file:
      - .env
    depends_on:
      - firebase

  users-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/users
    ports:
      - "127.0.0.1:3002:$PORT"
    environment:
      SERVER_TO_RUN: http
    env_file:
      - .env
    depends_on:
      - firebase

  users-grpc:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/users
    ports:
      - "127.0.0.1:3020:$PORT"
    environment:
      SERVER_TO_RUN: grpc
    env_file:
      - .env
    depends_on:
      - firebase

  firebase:
    # image: karhoo/firestore-emulator:0.2.2
    build: 
      context: docker/firebase
      dockerfile: firebase.dockerfile
    container_name: firebase-emulator
    volumes:
      - ./firebase/emulators/:/opt/workspace:cached
      - ./firebase/bin/:/root/.cache:cached
      - ./firebase/config/:/root/.config:cached
    ## env_file:
    ##  - .env
    ports:
      - 4000:4000 # Emulator Suite UI
      - 5000:5000 # Firebase Auth
      ## - 5001:5001 # Clound Functions
      - 9000:9000 # Realtime Database
      - 8787:8787 # Cloud Firestore
      - 8085:8085 # Cloud Pub/Sub
    restart: unless-stopped
